name: Send to Owner

on:
  repository_dispatch:
    types: [new_message]

jobs:
  notify-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Send direct message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.CHAT_ID }}
        run: |
          MESSAGE="🚀 *Pesan Baru* dari QnA ZanDKav\n"
          MESSAGE+="━━━━━━━━━━━━━━━━\n"
          MESSAGE+="👤 Nama: ${{ github.event.client_payload.name }}\n"
          MESSAGE+="📱 Telegram: @${{ github.event.client_payload.telegram }}\n\n"
          MESSAGE+="💬 Pesan:\n${{ github.event.client_payload.message }}"

          curl -s -X POST \
          "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
          -d chat_id="$OWNER_ID" \
          -d text="$MESSAGE" \
          -d parse_mode="Markdown"
