name: Send to Owner

on:
  repository_dispatch:
    types: [new_message]

jobs:
  notify-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: "7849712634"  # Langsung pakai ID owner
        run: |
          curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
          -d chat_id="$OWNER_ID" \
          -d text="📩 Pesan Baru dari QnA%0A━━━━━━━━━━%0Nama: ${{ github.event.client_payload.name }}%0Telegram: @${{ github.event.client_payload.telegram }}%0%0Pesan:%0${{ github.event.client_payload.message }}" \
          -d parse_mode="HTML"
